/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import controller.DAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.NhanVien;
import model.QUAYCAFE;
/**
 *
 * @author nghia
 */
public class ThongTinNhanVien extends javax.swing.JFrame {
    private ArrayList<NhanVien> dsnv;

    /**
     * Creates new form ThongTinNhanVien
     */
    public ThongTinNhanVien() {
        initComponents();
        overRide();
        NhanVien nv = new DAO().getNhanVien();
        textMaNhanVien.setText(Integer.toString(nv.getMA_NV()));
        textHo.setText(nv.getHO());
        textTen.setText(nv.getTEN());
        textDiaChi.setText(nv.getDIA_CHI());
        textSDT.setText(nv.getSDT());
        textTrangThaiNghi.setText(nv.getTT_NGHI());
    }

    public void nhanVien(){
        textTrangThaiNghi.setEnabled(false);
    }
    
    private void overRide(){
        setLocationRelativeTo(this);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textHo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textTen = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textSDT = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textDiaChi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textMaNhanVien = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textTrangThaiNghi = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        buttonLuu = new javax.swing.JButton();
        buttonChinhSua = new javax.swing.JButton();
        buttonThoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Họ Nhân Viên");

        textHo.setEnabled(false);
        textHo.setPreferredSize(new java.awt.Dimension(170, 28));

        jLabel2.setText("Tên Nhân Viên");

        textTen.setEnabled(false);
        textTen.setPreferredSize(new java.awt.Dimension(170, 28));

        jLabel3.setText("Số Điện Thoại");

        textSDT.setEnabled(false);
        textSDT.setPreferredSize(new java.awt.Dimension(170, 28));

        jLabel4.setText("Địa Chỉ");

        textDiaChi.setEnabled(false);
        textDiaChi.setPreferredSize(new java.awt.Dimension(170, 28));

        jLabel5.setText("Mã Nhân Viên");

        textMaNhanVien.setEnabled(false);
        textMaNhanVien.setPreferredSize(new java.awt.Dimension(170, 28));
        textMaNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMaNhanVienActionPerformed(evt);
            }
        });

        jLabel6.setText("Trạng Thái Nghỉ");

        textTrangThaiNghi.setEnabled(false);
        textTrangThaiNghi.setPreferredSize(new java.awt.Dimension(170, 28));
        textTrangThaiNghi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTrangThaiNghiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel5)
                                .addGap(6, 6, 6)
                                .addComponent(textMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(jLabel3)
                                .addGap(17, 17, 17)
                                .addComponent(textSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel1)
                                .addGap(8, 8, 8)
                                .addComponent(textHo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(jLabel4)
                                .addGap(51, 51, 51)
                                .addComponent(textDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel2)
                        .addGap(5, 5, 5)
                        .addComponent(textTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textTrangThaiNghi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textHo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textTrangThaiNghi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setMinimumSize(new java.awt.Dimension(50, 50));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 50));

        buttonLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/floppy-disk-16.png"))); // NOI18N
        buttonLuu.setText("Lưu");
        buttonLuu.setEnabled(false);
        buttonLuu.setPreferredSize(new java.awt.Dimension(85, 28));
        buttonLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLuuActionPerformed(evt);
            }
        });
        jPanel2.add(buttonLuu);

        buttonChinhSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/edit-info-16.png"))); // NOI18N
        buttonChinhSua.setText("Chỉnh Sửa");
        buttonChinhSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonChinhSuaActionPerformed(evt);
            }
        });
        jPanel2.add(buttonChinhSua);

        buttonThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exit-16.png"))); // NOI18N
        buttonThoat.setText("Thoát");
        buttonThoat.setPreferredSize(new java.awt.Dimension(85, 28));
        buttonThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonThoatActionPerformed(evt);
            }
        });
        jPanel2.add(buttonThoat);

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonChinhSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonChinhSuaActionPerformed
        // TODO add your handling code here:
        textHo.setEnabled(true);
        textTen.setEnabled(true);
        textSDT.setEnabled(true);
        textDiaChi.setEnabled(true);
//        checkBoxNghiViec.setEnabled(true);
        buttonLuu.setEnabled(true);
    }//GEN-LAST:event_buttonChinhSuaActionPerformed

    private void buttonThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonThoatActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_buttonThoatActionPerformed

    private void textMaNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMaNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textMaNhanVienActionPerformed

    private void buttonLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLuuActionPerformed
        // TODO add your handling code here:
        
        NhanVien nv = new NhanVien();
        nv.setHO(textHo.getText());
        nv.setTEN(textTen.getText());
        nv.setDIA_CHI(textDiaChi.getText());
        nv.setSDT(textSDT.getText());       
        if (new DAO().updateNHAN_VIEN(nv)) {
            JOptionPane.showMessageDialog(rootPane, "Chinh sua thong tin thanh cong!");
        } else{
            JOptionPane.showMessageDialog(rootPane, "Khong the chinh sua thong tin! ");     
        }       
    }//GEN-LAST:event_buttonLuuActionPerformed

    private void textTrangThaiNghiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTrangThaiNghiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTrangThaiNghiActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ThongTinNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ThongTinNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ThongTinNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ThongTinNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ThongTinNhanVien().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonChinhSua;
    private javax.swing.JButton buttonLuu;
    private javax.swing.JButton buttonThoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField textDiaChi;
    private javax.swing.JTextField textHo;
    private javax.swing.JTextField textMaNhanVien;
    private javax.swing.JTextField textSDT;
    private javax.swing.JTextField textTen;
    private javax.swing.JTextField textTrangThaiNghi;
    // End of variables declaration//GEN-END:variables
}
